name: Github Pages
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - uses: actions/setup-node@master
      with:
        node-version: latest
    - name: npm install
      run: |
        npm install
    - name: npm build
      run: |
        npm run debug
