name: Github Pages
on:
  push:
    branches:
      - master
jobs:
  install_build_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: npm install
      run: |
        npm install
    - name: npm build
      run: |
        npm run build
        touch _site/.nojekyll
        cat package.json | jq --raw-output ".name" > _site/CNAME
    - name: deploy
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_site
        SCRIPT_MODE: true
      run: |
        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
        bash ./entrypoint.sh
